### ISSUE TITLE
[Bug]: FastAPI Error

### ISSUE THREAD

**Issue by Vrk3ds** [brkirch/stable-diffusion-webui#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Upon trying to launch, I get the following error

Traceback (most recent call last):
File "/Users/scottd/autosd/launch.py", line 382, in 
start()
File "/Users/scottd/autosd/launch.py", line 373, in start
import webui
File "/Users/scottd/autosd/webui.py", line 8, in 
from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'

### Steps to reproduce the problem

launch ./webui.sh
the error happens before completely finishing the launch of Automatic1111

### What should have happened?

App should have launched successfully.

### Commit where the problem happens

https://github.com/brkirch/stable-diffusion-webui/releases/tag/20230416_experimental

### What platforms do you use to access the UI ?

MacOS

### What browsers do you use to access the UI ?

Apple Safari

### Command Line Arguments

```Shell
I haven't changed anything away from the default arguments.
```

### List of extensions

Default extensions

### Console logs

```Shell
################################################################
                          **WARNING**
  This is a test build of stable-diffusion-webui and PyTorch!
Crashes and bugs are expected, do not assume it will be stable!
   DO NOT report issues to the web UI or PyTorch developers!
Report issues to github.com/brkirch/stable-diffusion-webui/issues
################################################################

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on scottd user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.10 (main, Apr  9 2023, 20:06:33) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Commit hash: 106c9ac512b94fab83c02514f9a0821673ac9442
Launching Web UI with arguments: --no-download-sd-model --precision full --no-half-vae --upcast-sampling --opt-sub-quad-attention --use-cpu interrogate
Traceback (most recent call last):
  File "/Users/scottd/autosd/launch.py", line 382, in <module>
    start()
  File "/Users/scottd/autosd/launch.py", line 373, in start
    import webui
  File "/Users/scottd/autosd/webui.py", line 8, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
```

### Additional information

I have tried to uninstall fastAPI, re-install fastApi
activate venv and uninstall fastapi, re-install fastapi
update homebrew.... uninstall fastapi, re-install fast API

**Comment by brkirch** [comment]
This error is likely because the python packages failed to install during initial installation or `webui-user.sh` has defined a different venv directory. Is this with a new install or did you update an existing one?

**Comment by Vrk3ds** [comment]
It is a brand new install but I do have the normal automatic1111 installed as well.

**Comment by brkirch** [comment]
Did you use the installer? If you either cloned this repo or are attempting to use the source code directly it won't work. This repo is only intended to be installed and updated using the installers [here](https://github.com/brkirch/stable-diffusion-webui/releases). None of the dependencies nor the repo itself should be updated or installed manually.
